import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

import { Footer, Navbar } from '@/components/layout';

import './globals.css';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: `What you maybe don't know`,
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="pageWrapper bgGrayToblue">
          <Navbar />
          <main className="flex-1 flex justify-center items-center overflow-y-scroll">
            {children}
          </main>
          <Footer />
        </div>
      </body>
    </html>
  );
}
