import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

import { Footer, Navbar } from '@/components';

import './globals.css';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: `What you maybe don't know`,
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} relative min-h-screen flexCol bgBlueToPink`}
      >
        <Navbar />
        <main className="relative flex flex-col justify-center align-middle">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
